Add missing imports
This change fixes the following errors with ghc-9.6:

  lib/Language/Souffle/Interpreted.hs:305:9: error: [GHC-88464]
      Variable not in scope:
        forM_

  lib/Language/Souffle/Compiled.hs:214:3: error: [GHC-88464]
      Variable not in scope:
        when :: Bool -> CMarshalSlow () -> CMarshalSlow ()
      |
  214 |   when (byteCount + offset > totalByteCount) $ do